In [4]:

import numpy as np
import pandas as pd
print(pd.__version__)

1.3.5

In [5]:
books= pd.read_csv('books.csv')
users = pd.read_csv('users.csv')
ratings = pd.read_csv('ratings.csv')

c:\Project_files_Jan\Book_recommend_system\recommender_system_env\lib\site-packages\IPython\core\interactiveshell.py:3553: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [6]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [7]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [8]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [9]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [10]:
## Check NULL values
print(books.isnull().sum())

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [11]:
print(ratings.isnull().sum())

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [12]:
print(users.isnull().sum())

User-ID          0
Location         0
Age         110762
dtype: int64

In [13]:
## Duplicates checkings
books.duplicated().sum()

0

In [14]:
ratings.duplicated().sum()

0

In [15]:
users.duplicated().sum()

0

In [16]:
## Popularity based  recommendation system

In [17]:
# will consider top 50 books whose ratings got minimum 250 votes
# merge ratings and books

ratings_with_name = ratings.merge(books, on='ISBN')

In [18]:
ratings_with_name.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [19]:
number_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
number_rating_df.rename(columns={'Book-Rating': 'number_ratings'}, inplace=True)
number_rating_df.dtypes

Book-Title        object
number_ratings     int64
dtype: object

In [20]:
# Calculate average rating for each book title
average_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()

# Rename the 'Book-Rating' column to 'average_ratings'
average_rating_df.rename(columns={'Book-Rating': 'average_ratings'}, inplace=True)

# Print the resulting DataFrame
print(average_rating_df)

                                               Book-Title  average_ratings
0        A Light in the Storm: The Civil War Diary of ...         2.250000
1                                   Always Have Popsicles         0.000000
2                    Apple Magic (The Collector's series)         0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...         8.000000
4        Beyond IBM: Leadership Marketing and Finance ...         0.000000
...                                                   ...              ...
241066                                      Ã?Â?lpiraten.         0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.         5.250000
241068                                Ã?Â?sterlich leben.         7.000000
241069                              Ã?Â?stlich der Berge.         2.666667
241070                                  Ã?Â?thique en toc         4.000000

[241071 rows x 2 columns]

In [21]:

## merging number_rating_df and average_rating_df

Popular_df= number_rating_df.merge(average_rating_df, on='Book-Title')
Popular_df.columns

Index(['Book-Title', 'number_ratings', 'average_ratings'], dtype='object')

In [22]:
## Will take only books which have minimum 250 number of ratings
Popular_df.columns
Popular_df =  Popular_df[Popular_df['number_ratings']>=250].sort_values('average_ratings', ascending=False)
Popular_df.shape

(186, 3)

In [23]:
## Final Popular_df is ready
Popular_df = Popular_df.merge(books, on= 'Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author', 'Image-URL-M', 'number_ratings', 'average_ratings']]

In [24]:
Popular_df.shape

(186, 5)

In [25]:
### NOW WE LOOK FOR COLLOBORATIVE FILTERING RECOMMENDER SYSTEM

## will create df with books as rows, and user as columns
## will take user rating who rated more than 200 books (user>200)
## will take popular 50 books only

In [26]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [27]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating']>200
read_books_users= x[x].index ## who voted 200 books more

In [28]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(read_books_users)]
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [29]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >=50
famous_books = y[y].index

In [30]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [31]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [32]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [33]:
pt = final_ratings.pivot_table(index= 'Book-Title', columns= 'User-ID',values= 'Book-Rating' )

In [34]:
pt.fillna(0, inplace=True)

In [35]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [36]:
## to get ner by ratings books when user search for a books to get recommended near by ratings 4 books
## need to calculate euclidian distance

from sklearn.metrics.pairwise import cosine_similarity

In [37]:
similarity_scores = cosine_similarity(pt)

In [38]:
similarity_scores[705]

array([0.04316046, 0.14263397, 0.10796119, 0.        , 0.01520436,
       0.03108033, 0.0522013 , 0.01957649, 0.12494756, 0.05477189,
       0.13656453, 0.13714049, 0.34845731, 0.02423182, 0.048597  ,
       0.02447346, 0.0195196 , 0.16018605, 0.02820049, 0.05402226,
       0.09713015, 0.01165403, 0.06615204, 0.05740687, 0.07773304,
       0.        , 0.01652917, 0.01726685, 0.02490325, 0.04252513,
       0.00860251, 0.01650084, 0.02038066, 0.007485  , 0.04410832,
       0.13011028, 0.0657527 , 0.21359264, 0.02923857, 0.11116717,
       0.        , 0.06176826, 0.04428081, 0.01355567, 0.06323007,
       0.05977839, 0.09142173, 0.08395217, 0.09523283, 0.06678121,
       0.1008422 , 0.06479029, 0.05007515, 0.07387598, 0.02151476,
       0.        , 0.30880884, 0.00624948, 0.09578947, 0.06655935,
       0.01991675, 0.        , 0.01389599, 0.11079246, 0.        ,
       0.02328262, 0.02183012, 0.        , 0.0122129 , 0.0691775 ,
       0.07102834, 0.        , 0.10006734, 0.08423872, 0.16269222,
       0.07349448, 0.03972365, 0.0183372 , 0.01491491, 0.02085306,
       0.02947659, 0.10253677, 0.01036933, 0.        , 0.00797687,
       0.1388951 , 0.07592468, 0.05474923, 0.00686115, 0.0282024 ,
       0.42411899, 0.        , 0.08323429, 0.        , 0.01197241,
       0.12167896, 0.20717179, 0.06813128, 0.0981776 , 0.        ,
       0.06919505, 0.        , 0.11573414, 0.05101987, 0.01385546,
       0.081501  , 0.15218944, 0.1223431 , 0.03147357, 0.08861692,
       0.02370416, 0.02349721, 0.        , 0.06714482, 0.04182909,
       0.0767546 , 0.04954063, 0.01855873, 0.02034221, 0.        ,
       0.0063053 , 0.05517466, 0.01583589, 0.07113376, 0.        ,
       0.13577365, 0.03310167, 0.04602183, 0.3427642 , 0.07754383,
       0.14785462, 0.12561228, 0.10528675, 0.        , 0.        ,
       0.        , 0.01963495, 0.08652384, 0.06480786, 0.08924415,
       0.02700291, 0.03148287, 0.12056404, 0.09243576, 0.14503688,
       0.06396909, 0.01984658, 0.12313889, 0.02383103, 0.18449927,
       0.0190607 , 0.11893192, 0.02948692, 0.06833985, 0.02921136,
       0.02011462, 0.07225929, 0.        , 0.14975673, 0.00988157,
       0.        , 0.        , 0.01435248, 0.0292431 , 0.19729212,
       0.38779914, 0.14873348, 0.08963161, 0.01604882, 0.08941697,
       0.01842722, 0.02887854, 0.03071043, 0.11774892, 0.0722923 ,
       0.19198532, 0.        , 0.26112527, 0.34475274, 0.        ,
       0.08543029, 0.00415961, 0.01697825, 0.01321288, 0.0245294 ,
       0.03150231, 0.07406512, 0.10357891, 0.01245091, 0.04088046,
       0.08185094, 0.03568491, 0.09246504, 0.19143054, 0.12167625,
       0.07198422, 0.08684362, 0.01083931, 0.06453912, 0.02662224,
       0.02755513, 0.        , 0.03334606, 0.01693878, 0.1686093 ,
       0.22092687, 0.06357396, 0.26794018, 0.0698757 , 0.06360981,
       0.03097224, 0.32862749, 0.15914609, 0.06364733, 0.05643521,
       0.        , 0.        , 0.01861491, 0.01120864, 0.04384115,
       0.02725873, 0.12879699, 0.        , 0.0222708 , 0.41192699,
       0.04895294, 0.1723974 , 0.08493068, 0.1120641 , 0.05777432,
       0.06682843, 0.12465283, 0.09743486, 0.04034135, 0.0736237 ,
       0.15200104, 0.01903001, 0.        , 0.03751227, 0.09293554,
       0.02131873, 0.02345652, 0.19184065, 0.03791129, 0.04736288,
       0.25001718, 0.09783273, 0.08898284, 0.        , 0.03411807,
       0.27859162, 0.01249319, 0.01382732, 0.06345476, 0.07898133,
       0.02196858, 0.43518289, 0.01816353, 0.02949122, 0.08860101,
       0.08545236, 0.        , 0.01906805, 0.        , 0.        ,
       0.02084584, 0.        , 0.10862654, 0.01500206, 0.0299738 ,
       0.05595307, 0.        , 0.03346327, 0.        , 0.11923441,
       0.1278937 , 0.02649577, 0.13118033, 0.34461003, 0.13083444,
       0.0509615 , 0.        , 0.00992364, 0.03226463, 0.08088954,
       0.05566939, 0.12315804, 0.37390747, 0.16782601, 0.06894834,
       0.05558645, 0.08980439, 0.01319224, 0.02202505, 0.27687513,
       0.01412188, 0.06507216, 0.02592236, 0.03296408, 0.17342769,
       0.01495353, 0.1025474 , 0.00587006, 0.12728781, 0.02081515,
       0.14780927, 0.        , 0.01332122, 0.03728686, 0.        ,
       0.02251533, 0.15610509, 0.05084246, 0.26653097, 0.02890685,
       0.        , 0.        , 0.        , 0.01523766, 0.02539731,
       0.01938078, 0.16223835, 0.15160706, 0.00957229, 0.03526097,
       0.01885565, 0.09682211, 0.        , 0.01046316, 0.09048525,
       0.02040832, 0.07482239, 0.0205191 , 0.16452847, 0.07250522,
       0.13517032, 0.        , 0.03572688, 0.18259038, 0.03300169,
       0.        , 0.10016494, 0.02867712, 0.12403795, 0.01415506,
       0.06777028, 0.        , 0.0148812 , 0.03014101, 0.01790489,
       0.07857146, 0.02243205, 0.10877257, 0.10013527, 0.17340594,
       0.10163162, 0.07611856, 0.        , 0.0815631 , 0.0329266 ,
       0.        , 0.08270306, 0.07046976, 0.06809613, 0.10708582,
       0.09152198, 0.        , 0.        , 0.08538995, 0.25084248,
       0.02012906, 0.        , 0.1058498 , 0.05617315, 0.08995864,
       0.        , 0.11099108, 0.        , 0.        , 0.09345958,
       0.10304712, 0.06738394, 0.07366885, 0.05843509, 0.02017863,
       0.11588232, 0.09530173, 0.04031952, 0.06485852, 0.06232682,
       0.        , 0.13268475, 0.01333437, 0.03625922, 0.39474454,
       0.02573298, 0.07707535, 0.09784027, 0.08989996, 0.        ,
       0.10066094, 0.0173154 , 0.05897175, 0.        , 0.03257048,
       0.07257141, 0.12120033, 0.12161813, 0.10143332, 0.03430928,
       0.00761423, 0.0260864 , 0.02225846, 0.01238412, 0.09739603,
       0.10753022, 0.03163043, 0.02131342, 0.06147162, 0.10116827,
       0.01818026, 0.06279894, 0.03331343, 0.01923824, 0.12455241,
       0.08672055, 0.        , 0.12626458, 0.10954651, 0.13115424,
       0.06024643, 0.12468451, 0.07895368, 0.07757818, 0.08279969,
       0.05829863, 0.20300214, 0.12258395, 0.01751067, 0.075895  ,
       0.09247355, 0.02371086, 0.        , 0.00804651, 0.01305758,
       0.02576914, 0.02581612, 0.01509534, 0.02145305, 0.        ,
       0.        , 0.0123931 , 0.08153778, 0.        , 0.12750002,
       0.        , 0.14104481, 0.07231392, 0.03112319, 0.03184228,
       0.12375981, 0.03002931, 0.14018063, 0.03945321, 0.11417646,
       0.05022779, 0.16350792, 0.10257808, 0.05520808, 0.        ,
       0.        , 0.        , 0.0211541 , 0.        , 0.0209802 ,
       0.05730798, 0.10436482, 0.        , 0.01971139, 0.02486193,
       0.09825165, 0.01351201, 0.01396407, 0.04872199, 0.0495299 ,
       0.01130987, 0.08855256, 0.21193621, 0.06468232, 0.        ,
       0.01647247, 0.        , 0.05571597, 0.11082816, 0.05145678,
       0.0939795 , 0.00976729, 0.03796752, 0.        , 0.17184374,
       0.00796816, 0.11810443, 0.05525476, 0.05850902, 0.05136523,
       0.10372385, 0.16454962, 0.07735076, 0.05870361, 0.19260823,
       0.14404392, 0.        , 0.03023848, 0.08799553, 0.07019703,
       0.02063915, 0.09568985, 0.0528802 , 0.08736816, 0.01378923,
       0.04839216, 0.0256067 , 0.01433467, 0.14373304, 0.0240561 ,
       0.        , 0.20378286, 0.00643274, 0.07893569, 0.03919489,
       0.09253142, 0.02427087, 0.02441902, 0.02595738, 0.06763876,
       0.07699744, 0.00617037, 0.18648767, 0.08242229, 0.04463949,
       0.04930958, 0.04754669, 0.07397736, 0.11293172, 0.01355306,
       0.04550398, 0.00674451, 0.        , 0.06402957, 0.00175129,
       0.08359891, 0.01080385, 0.03290435, 0.02680665, 0.06958093,
       0.0168865 , 0.01388401, 0.01091428, 0.05983041, 0.06065114,
       0.04658926, 0.11545176, 0.0586013 , 0.13691686, 0.02015586,
       0.        , 0.1478327 , 0.06546487, 0.09923839, 0.10535229,
       0.03235262, 0.04905606, 0.        , 0.0672879 , 0.01172807,
       0.15073393, 0.03906862, 0.01704999, 0.06548174, 0.11610353,
       0.06610758, 0.05218123, 0.14813444, 0.06963871, 0.0256665 ,
       0.        , 0.05201621, 0.02549325, 0.06270659, 0.        ,
       0.01734303, 0.1097025 , 0.06007474, 0.        , 0.01289818,
       0.05570493, 0.01594052, 0.05471612, 0.0722237 , 0.02793562,
       0.12367699, 0.02272545, 0.10220263, 0.05528711, 0.01913349,
       0.02077888, 0.04738633, 0.17346874, 0.        , 0.04635747,
       0.01706917, 0.03761134, 0.03246934, 0.1533169 , 0.00194563,
       0.01851853, 0.14059042, 0.        , 0.01808072, 0.02334905,
       0.11220632, 0.03152608, 0.05440975, 0.08466203, 0.01363173,
       0.03223479, 0.01666817, 0.02772901, 0.1372602 , 0.01173955,
       0.10996363, 0.00853165, 0.11405339, 0.03452708, 0.02516027,
       0.07310645, 0.02051005, 0.08657144, 0.0228256 , 0.06009946,
       0.03256119, 0.12494147, 0.03155771, 0.        , 0.0192766 ,
       0.        , 0.17805109, 0.05058818, 0.01772579, 0.06839015,
       0.04271069, 0.17797715, 0.04296866, 0.02759238, 0.02092205,
       0.02374474, 0.03368759, 0.08795312, 0.        , 0.13580675,
       0.07830028, 0.19814751, 0.10353987, 0.07636253, 0.01655835,
       0.        , 0.01538407, 0.        , 0.01188136, 0.        ,
       0.01955086, 0.07369833, 0.02213438, 0.01062866, 0.07279966,
       0.02222484, 0.0765093 , 0.0982387 , 0.02315145, 0.04215034,
       0.02060255, 0.        , 0.04766702, 0.07809228, 0.0299461 ,
       0.04559086, 0.10750421, 0.        , 0.02211337, 0.07267231,
       0.07613136, 0.        , 0.04480079, 0.02696629, 0.01831426,
       0.06692654, 0.17062271, 0.14513761, 0.13640274, 0.10649491,
       0.0468805 , 0.        , 0.1906585 , 0.0196177 , 0.10602962,
       1.        ])

In [39]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:5]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [40]:
recommend('The Notebook')

[['A Walk to Remember',
  'Nicholas Sparks',
  'http://images.amazon.com/images/P/0446608955.01.MZZZZZZZ.jpg'],
 ['The Rescue',
  'Nicholas Sparks',
  'http://images.amazon.com/images/P/0446610399.01.MZZZZZZZ.jpg'],
 ['One Door Away from Heaven',
  'Dean R. Koontz',
  'http://images.amazon.com/images/P/0553582755.01.MZZZZZZZ.jpg'],
 ['Toxin',
  'Robin Cook',
  'http://images.amazon.com/images/P/0425166619.01.MZZZZZZZ.jpg']]

In [42]:
## Saving df df to pickle

import pickle
pickle.dump(Popular_df,open('popular.pkl','wb'))
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))